name: Publisher

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch: # To enable a workflow to be triggered manually
    
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  publish:     
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        cache: true
        cache-dependency-path: |
          **/*.fsproj

    # Build only when pushing to master
    - name: Fake default target (master push)
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: dotnet fsi build.fsx -e FAKE_DETAILED_ERRORS=true -e GITHUB_NUGET_TOKEN=${{ secrets.PUBLISH_TO_NUGET_ORG }}

    # Test for PRs and non-master branches
    - name: Fake Test target (PRs and non-master)
      if: ${{ !(github.event_name == 'push' && github.ref == 'refs/heads/master') }}
      run: dotnet fsi build.fsx -e FAKE_DETAILED_ERRORS=true -e GITHUB_NUGET_TOKEN=${{ secrets.PUBLISH_TO_NUGET_ORG }} -t Test
